### ISSUE TITLE
Is there any plan to support to resume checkpoint including model weight, optimizer parameters, lr, epoch, and others?

### ISSUE THREAD

**Issue by zhangchbin** [Megvii-BaseDetection/cvpods#10]

**Comment by poodarchu** [comment]
Those features have already been implemented in cvpods.

you can use `--resume` to resume the training process, and all the saved ckpts can be found at OUTPUT_DIR (you could see a 'log' softlink under each experiment's directory).

**Comment by zhangchbin** [comment]
Can it resume the parameters of the optimizer, the lr and others?

**Comment by FateScript** [comment]
Yes, it can
