### ISSUE TITLE
[BUG] Installation problem with Pytorch version >= 1.11

### ISSUE THREAD

**Issue by alexbui91** [Megvii-BaseDetection/cvpods#103]
In order for us to know the problem you are facing more quickly, please provide the following basic information.

1. **OS version**：_e.g. Ubuntu 20.04_
2. **Environment version:**  _Python 3.8 / PyTorch 1.12 / CUDA 11.3 
3. **cvpods version**：commit id_ 2deea5dc659371318c8a570c644201d913a83027

I ran the following command：
```
git clone https://github.com/Megvii-BaseDetection/cvpods.git
pip install -e cvpods --user 
```

Actual results：
```
/home/alexbui/Downloads/cvpods/cvpods/layers/csrc/border_align/border_align_kernel.cu:6:10: fatal error: THC/THC.h: No such file or directory
            6 | #include <THC/THC.h>
              |          ^~~~~~~~~~~
        compilation terminated.
        /home/alexbui/anaconda3/envs/pyg/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /home/alexbui/anaconda3/envs/pyg/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /home/alexbui/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
        [end of output]
```

I searched on the internet and founded out that THC.h was deprecated from the Pytorch version 1.11. When I downgraded Pytorch to version 1.10, the installation worked well. Please consider upgrading the thc.h code to aten namespace correspondingly. Thank you very much!!

**Comment by poodarchu** [comment]
//Comment Out
//#include <THE/THC.h>
//extern THCState *state;
//cudaStream_t stream = THCState_getCurrentStream(state);

//Replace with
#include <ATen/cuda/CUDAContext.h>
#include <ATen/cuda/CUDAEvent.h>
cudaStream_t stream = at::cuda::getCurrentCUDAStream();
