### ISSUE TITLE
ImportError: cannot import name 'PSRoIAlign

### ISSUE THREAD

**Issue by ChengJianjia** [Megvii-BaseDetection/cvpods#13]
My version:
pytorch:1.3.2
torchvision:0.4.2

Is this a problem about enviroment?

**Comment by poodarchu** [comment]
Have you built cvpods with GPU? You can put your compiling log or error message here.

**Comment by FateScript** [comment]
> My version:
> pytorch:1.3.2
> torchvision:0.4.2
> 
> Is this a problem about enviroment?

It seems your torchvision version doesn't support PSRoIAlign, you could solve this issue by upgrade your torch and torchvison or simplely comment [this line of code](https://github.com/Megvii-BaseDetection/cvpods/blob/master/cvpods/modeling/poolers.py#L8).

**Comment by ChengJianjia** [comment]
> > My version:
> > pytorch:1.3.2
> > torchvision:0.4.2
> > Is this a problem about enviroment?
> 
> It seems your torchvision version doesn't support PSRoIAlign, you could solve this issue by upgrade your torch and torchvison or simplely comment [this line of code](https://github.com/Megvii-BaseDetection/cvpods/blob/master/cvpods/modeling/poolers.py#L8).

I will try to update torchvision. 
 what version in your program?
Thanks for reply

**Comment by FateScript** [comment]
You could try torch >= 1.6.0 and matched torchvison version, which support PSRoI op.
