### ISSUE TITLE
找不到 config

### ISSUE THREAD

**Issue by smartadpole** [Megvii-BaseDetection/cvpods#15]
**Please use this template to submit your problem or your question will _NOT_ be properly tackled.**

* We recommend that you check the existing issues before creating a new issue to see if anyone has encountered the same issue as you. 
* Please check whether the software version is the latest version first. If not, you can try to update to the latest version and see if the problem is resolved.

---

In order for us to know the problem you are facing more quickly, please provide the following basic information.

1. **OS version**：_e.g. Ubuntu 18.04_
2. **Environment version:**  _Python / PyTorch / CUDA / cuDNN version_
3. **cvpods version**： latest

run    
```
python3 train_net.py
```
bug    
```
from config import config  # noqa: E402
ModuleNotFoundError: No module named 'config'

```

**Comment by smartadpole** [comment]
解决了，要切到网络配置的目标目录下才能执行 命令；

**Comment by poodarchu** [comment]
donot call `python3 train_net.py` like you use before.
use `pods_train --num-gpus 8` in your **experiments directory**

**Comment by smartadpole** [comment]
> donot call `python3 train_net.py` like you use before.
> use `pods_train --num-gpus 8` in your **experiments directory**

got it
