### ISSUE TITLE
[Usage] How to register custom datasets?

### ISSUE THREAD

**Issue by 2gunsu** [Megvii-BaseDetection/cvpods#19]
**Please use this template to submit your problem or your question will _NOT_ be properly tackled.**

---

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?

Hi.
Thank you for sharing this great project and I have one question.

According to your document
(https://cvpods.readthedocs.io/en/latest/tutorials/datasets.html#update-the-config-for-new-datasets),
in order to register a dataset in COCO format, it is stated to proceed as follows.

```python
from cvpods.data.datasets import register_coco_instances
register_coco_instances("my_dataset", {}, "json_annotation.json", "path/to/image/dir")
```

However, it seems that the method 'register_coco_instances' no longer exists. 
Can you tell me how to register the custom dataset?
Sorry for bothering you.

**Comment by poodarchu** [comment]
We're sorry for the misunderstanding. Documents will be updated and currently it's out of date (except the API references).
As for now, you can refer to the [cvpods_tutorials](https://github.com/poodarchu/cvpods/blob/master/docs/tutorials/cvpods%20tutorials.ipynb) for instructions of adding custom datasets.

**Comment by 2gunsu** [comment]
Thank you!
Have a nice day :)
