### ISSUE TITLE
About crowdhuman dataset

### ISSUE THREAD

**Issue by Brizel** [Megvii-BaseDetection/cvpods#3]
I follow your instruction and linked my dataset successfully, but I got an error when running _crowdhuman.py_:

 File "/home/chnchen/.local/lib/python3.6/site-packages/cvpods-0.1-py3.6-linux-x86_64.egg/cvpods/data/datasets/crowdhuman.py", line 169, in _load_annotations
    record["height"] = anno_dict["height"]
KeyError: 'height'

and I checked the related codes from line 161 - 171:

ann_keys = ["tag", "hbox", "vbox", "head_attr", "extra"]
        for anno_str in gt_records:
            print(anno_str)

            anno_dict = json.loads(anno_str)
            print(anno_dict)
            record = {}
            record["file_name"] = os.path.join(image_root, "{}.jpg".format(anno_dict["ID"]))
            record["height"] = anno_dict["height"]
            record["width"] = anno_dict["width"]
            record["image_id"] = anno_dict["ID"]

I think this code is trying to read gt boxes and image sizes from _annotation_train.odgt_ but the annotation_train just stored the ID info without image sizes.

After commeting ：
            record["height"] = anno_dict["height"]
            record["width"] = anno_dict["width"]
the training process can be started with no errors.

**Comment by poodarchu** [comment]
Thanks for pointing out this issue, we add  'height' and 'width' keys to the original odgt, you can just comment them.
