### ISSUE TITLE
Optical flow, scene flow, depth[FEATURE]

### ISSUE THREAD

**Issue by a1600012888** [Megvii-BaseDetection/cvpods#38]
Hello, thanks for this great project! 

I am wondering if this project will include more tasks like, optical flow, 3d scene flow or depth estimation.  I can help contributing the code(But I don't have enough GPUs to reproduce sota results..).

**Comment by poodarchu** [comment]
It should be quite easy to add a new task or dataset following our guides, we can help if you have any questions.
