### ISSUE TITLE
[FEATURE] Multi-scale testing support ?

### ISSUE THREAD

**Issue by iFighting** [Megvii-BaseDetection/cvpods#47]
[FEATURE] Multi-scale testing support ?

**Comment by FateScript** [comment]
You might using [TTAWarper](https://github.com/Megvii-BaseDetection/cvpods/blob/07f53c9d10c42cdecd6123372e4d0e2683cbe61d/cvpods/modeling/test_time_augmentation.py#L341) to support Multiscale testing, We will add tutorial to doc soon.

**Comment by FateScript** [comment]
close this issue due to no reply for a week.
