### ISSUE TITLE
About test model in train mode

### ISSUE THREAD

**Issue by www516717402** [Megvii-BaseDetection/cvpods#51]
Suggest add a small data for train code since prepare huge dataset will get error somtimes and small dataset for comrehend this detect structure quickly.  Like [Yolov5](https://github.com/ultralytics/yolov5) coco 128 images.

**Comment by poodarchu** [comment]
If I understand what you mean correctly, we can provide an example using torchvision's CIFAR10 to train a classification model.

Does it satisfy your expectation?

**Comment by www516717402** [comment]
About detection Please offer a small dataset(such as 128 images subset in coco) for run cvpods rapidly.

**Comment by www516717402** [comment]
The above are all my thought. Close this issue.

**Comment by poodarchu** [comment]
we think providing a mini-dataset is not necessary. Users should prepare the dataset by themselves, not by us.
