### ISSUE TITLE
[Usage] How to use cvpods in slurm environment

### ISSUE THREAD

**Issue by 4-0-4-notfound** [Megvii-BaseDetection/cvpods#64]
**Please use this template to submit your need.**

---

**Is your feature request related to a problem? Please describe.**

when directly use `pods_train --num-gpus 1` , it would work fine in slurm environment
BUT, when `--num-gpus ` >1, it would get the following error:

```
[08/03 10:19:07] c2.engine.runner INFO: Starting training from iteration 0
[08/03 10:19:11] c2.engine.base_runner ERROR: Exception during training:
Traceback (most recent call last):
  File "/xxx/github/cvpods/cvpods/engine/base_runner.py", line 84, in train
    self.run_step()
  File "/xxx/github/cvpods/cvpods/engine/base_runner.py", line 185, in run_step
    loss_dict = self.model(data)
  File "/xxx/anaconda3/envs/cvpod/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/xxx/github/OTA/playground/detection/coco/ota.res50.fpn.coco.800size.1x/fcos.py", line 218, in forward
    gt_ious, box_cls, box_delta, box_iou)
  File "/xxx//github/OTA/playground/detection/coco/ota.res50.fpn.coco.800size.1x/fcos.py", line 383, in losses
    dist.all_reduce(num_foreground)
  File "/xxx/anaconda3/envs/cvpod/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 953, in all_reduce
    _check_default_pg()
  File "//xxx/anaconda3/envs/cvpod/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

-- Process 0 terminated with the following error:    
Traceback (most recent call last):  File "/xxx/anaconda3/envs/cvpod/lib/python3.6/site-ackages/torch/multiprocessing/spawn.py", line 19, in _wrapfn(i, *args)
  File "/xxx/github/cvpods/cvpods/engine/launch.py", line 71, in _distributed_worker
    raise e  File "/xxx/github/cvpods/cvpods/engine/launch.py", line 66, in _distributed_worker

  backend="NCCL", init_method=dist_url, world_size=world_size, rank=global_rank                                             
   File "/xxx/anaconda3/envs/cvpod/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 4$5, in init_process_group barrier()      
File "/xxx/anaconda3/envs/cvpod/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1$60, in barrier 
 work = _default_pg.barrier()    
 RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370116979/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid $sage, NCCL version 2.7.8                                               
```

**Describe the solution you'd like**
support use in slurm environment

**Comment by tonysy** [comment]
It's related to the NCCL configuration. You may need to set `NCCL_SOCKET_IFNAME` and `GLOO_SOCKET_IFNAME` environment variables according to your local configuration

**Comment by 4-0-4-notfound** [comment]
> It's related to the NCCL configuration. You may need to set `NCCL_SOCKET_IFNAME` and `GLOO_SOCKET_IFNAME` environment variables according to your local configuration

In the original Pytorch DDP method, it is not needed to explictly set `NCCL_SOCKET_IFNAME` and `GLOO_SOCKET_IFNAME`  to use in slurm environment.
So, how to set `NCCL_SOCKET_IFNAME` and `GLOO_SOCKET_IFNAME` in cvpod, any suggestions?

**Comment by poodarchu** [comment]
replace launch in engine/launch.py with slurm_launch:

def slurm_launch(
    main_func,
    num_gpus_per_machine,
    num_machines=1,
    machine_rank=0,
    dist_url=None,
    port=None,
    backend="nccl",
    args=(),
    timeout=DEFAULT_TIMEOUT,
):
    """
    Launch multi-gpu or distributed training.
    This function must be called on all machines involved in the training.
    It will spawn child processes (defined by ``num_gpus_per_machine``) on each machine.
    Args:
        main_func: a function that will be called by `main_func(*args)`
        num_gpus_per_machine (int): number of GPUs per machine
        num_machines (int): the total number of machines
        machine_rank (int): the rank of this machine
        dist_url (str): url to connect to for distributed jobs, including protocol
                       e.g. "tcp://127.0.0.1:8686".
                       Can be set to "auto" to automatically select a free port on localhost
        timeout (timedelta): timeout of the distributed workers
        args (tuple): arguments passed to main_func
    """
    world_size = num_machines * num_gpus_per_machine
    if world_size > 1:
        # https://github.com/pytorch/pytorch/pull/14391
        # TODO prctl in spawned processes

        if dist_url == "auto":
            assert num_machines == 1, "dist_url=auto not supported in multi-machine jobs."
            port = _find_free_port()
            dist_url = f"tcp://127.0.0.1:{port}"
        if num_machines > 1 and dist_url.startswith("file://"):
            logger = logging.getLogger(__name__)
            logger.warning(
                "file:// is not a reliable init_method in multi-machine jobs. Prefer tcp://"
            )

        """Initialize slurm distributed training environment.
        If argument ``port`` is not specified, then the master port will be system
        environment variable ``MASTER_PORT``. If ``MASTER_PORT`` is not in system
        environment variable, then a default port ``29500`` will be used.
        Args:
            backend (str): Backend of torch.distributed.
            port (int, optional): Master port. Defaults to None.
        """
        proc_id = int(os.environ['SLURM_PROCID'])
        ntasks = int(os.environ['SLURM_NTASKS'])
        node_list = os.environ['SLURM_NODELIST']
        num_gpus = torch.cuda.device_count()
        torch.cuda.set_device(proc_id % num_gpus)
        addr = subprocess.getoutput(
            f'scontrol show hostname {node_list} | head -n1')
        # specify master port
        if port is not None:
            os.environ['MASTER_PORT'] = str(port)
        elif 'MASTER_PORT' in os.environ:
            pass  # use MASTER_PORT in the environment variable
        else:
            # 29500 is torch.distributed default port
            os.environ['MASTER_PORT'] = '29500'
        # use MASTER_ADDR in the environment variable if it already exists
        if 'MASTER_ADDR' not in os.environ:
            os.environ['MASTER_ADDR'] = addr
        os.environ['WORLD_SIZE'] = str(ntasks)
        os.environ['LOCAL_RANK'] = str(proc_id % num_gpus)
        os.environ['RANK'] = str(proc_id)
        dist.init_process_group(backend=backend)

        assert comm._LOCAL_PROCESS_GROUP is None
        num_machines = world_size // num_gpus_per_machine
        for i in range(num_machines):
            ranks_on_i = list(range(i * num_gpus_per_machine, (i + 1) * num_gpus_per_machine))
            pg = dist.new_group(ranks_on_i)
            if i == machine_rank:
                comm._LOCAL_PROCESS_GROUP = pg

        main_func(*args)
    else:
        main_func(*args)

**Comment by poodarchu** [comment]
@4-0-4-notfound 

You can replace the launch function in engine/launch.py with my slurm_launch function below:

```python
def slurm_launch(
    main_func,
    num_gpus_per_machine,
    num_machines=1,
    machine_rank=0,
    dist_url=None,
    port=None,
    backend="nccl",
    args=(),
    timeout=DEFAULT_TIMEOUT,
):
    """
    Launch multi-gpu or distributed training.
    This function must be called on all machines involved in the training.
    It will spawn child processes (defined by ``num_gpus_per_machine``) on each machine.
    Args:
        main_func: a function that will be called by `main_func(*args)`
        num_gpus_per_machine (int): number of GPUs per machine
        num_machines (int): the total number of machines
        machine_rank (int): the rank of this machine
        dist_url (str): url to connect to for distributed jobs, including protocol
                       e.g. "tcp://127.0.0.1:8686".
                       Can be set to "auto" to automatically select a free port on localhost
        timeout (timedelta): timeout of the distributed workers
        args (tuple): arguments passed to main_func
    """
    world_size = num_machines * num_gpus_per_machine
    if world_size > 1:
        # https://github.com/pytorch/pytorch/pull/14391
        # TODO prctl in spawned processes

        if dist_url == "auto":
            assert num_machines == 1, "dist_url=auto not supported in multi-machine jobs."
            port = _find_free_port()
            dist_url = f"tcp://127.0.0.1:{port}"
        if num_machines > 1 and dist_url.startswith("file://"):
            logger = logging.getLogger(__name__)
            logger.warning(
                "file:// is not a reliable init_method in multi-machine jobs. Prefer tcp://"
            )

        """Initialize slurm distributed training environment.
        If argument ``port`` is not specified, then the master port will be system
        environment variable ``MASTER_PORT``. If ``MASTER_PORT`` is not in system
        environment variable, then a default port ``29500`` will be used.
        Args:
            backend (str): Backend of torch.distributed.
            port (int, optional): Master port. Defaults to None.
        """
        proc_id = int(os.environ['SLURM_PROCID'])
        ntasks = int(os.environ['SLURM_NTASKS'])
        node_list = os.environ['SLURM_NODELIST']
        num_gpus = torch.cuda.device_count()
        torch.cuda.set_device(proc_id % num_gpus)
        addr = subprocess.getoutput(
            f'scontrol show hostname {node_list} | head -n1')
        # specify master port
        if port is not None:
            os.environ['MASTER_PORT'] = str(port)
        elif 'MASTER_PORT' in os.environ:
            pass  # use MASTER_PORT in the environment variable
        else:
            # 29500 is torch.distributed default port
            os.environ['MASTER_PORT'] = '29500'
        # use MASTER_ADDR in the environment variable if it already exists
        if 'MASTER_ADDR' not in os.environ:
            os.environ['MASTER_ADDR'] = addr
        os.environ['WORLD_SIZE'] = str(ntasks)
        os.environ['LOCAL_RANK'] = str(proc_id % num_gpus)
        os.environ['RANK'] = str(proc_id)
        dist.init_process_group(backend=backend)

        assert comm._LOCAL_PROCESS_GROUP is None
        num_machines = world_size // num_gpus_per_machine
        for i in range(num_machines):
            ranks_on_i = list(range(i * num_gpus_per_machine, (i + 1) * num_gpus_per_machine))
            pg = dist.new_group(ranks_on_i)
            if i == machine_rank:
                comm._LOCAL_PROCESS_GROUP = pg

        main_func(*args)
    else:
        main_func(*args)
```

**Comment by poodarchu** [comment]
@4-0-4-notfound 

I've tested this feature, and it can work perfectly.

**Comment by 4-0-4-notfound** [comment]
thanks for your reply, it works.

another question:
what does `_LOCAL_PROCESS_GROUP `  work for, which in the following code:
`      assert comm._LOCAL_PROCESS_GROUP is None
        num_machines = world_size // num_gpus_per_machine
        for i in range(num_machines):
            ranks_on_i = list(range(i * num_gpus_per_machine, (i + 1) * num_gpus_per_machine))
            pg = dist.new_group(ranks_on_i)
            if i == machine_rank:
                comm._LOCAL_PROCESS_GROUP = pg`

could i remove `_LOCAL_PROCESS_GROUP` in the slrum environment， and just using local rank and global rank ？

**Comment by poodarchu** [comment]
yes, you can remove it.
