### ISSUE TITLE
[BUG] tutorial for cvpods is not avaliable

### ISSUE THREAD

**Issue by x-x110** [Megvii-BaseDetection/cvpods#67]
During opening the https://github.com/poodarchu/cvpods/blob/master/docs/tutorials/cvpods%20tutorials.ipynb address, we get the 404 error.

**Comment by tbfly** [comment]
https://github.com/Megvii-BaseDetection/cvpods/blob/master/docs/tutorials/cvpods%20tutorials.ipynb

**Comment by FateScript** [comment]
> https://github.com/Megvii-BaseDetection/cvpods/blob/master/docs/tutorials/cvpods%20tutorials.ipynb

That's wired, tutorials are avaliable for me : (
![image](https://user-images.githubusercontent.com/12154809/139781620-d1f2633e-a53c-421e-89a8-955e2eadabe0.png)
