### ISSUE TITLE
Is there any plan to support FP16?

### ISSUE THREAD

**Issue by zhangchbin** [Megvii-BaseDetection/cvpods#7]

**Comment by poodarchu** [comment]
FP16 support will be added in a few days.

**Comment by poodarchu** [comment]
we have added support for FP 16 training, you can set ENABLE=True **in your experiment's config.py.**

FP 16 have been set to be disabled by default:
https://github.com/Megvii-BaseDetection/cvpods/blob/master/cvpods/configs/base_config.py#L179
