### ISSUE TITLE
[BUG]RuntimeError: Error compiling objects for extension, when i compile the cvpods in windows, i get above error, my environment is RTX 2090, cuda 11.1, pytorch 1.8.1

### ISSUE THREAD

**Issue by binyisu** [Megvii-BaseDetection/cvpods#70]
**Please use this template to submit your problem or your question will _NOT_ be properly tackled.**

* We recommend that you check the existing issues before creating a new issue to see if anyone has encountered the same issue as you. 
* Please check whether the software version is the latest version first. If not, you can try to update to the latest version and see if the problem is resolved.

---

In order for us to know the problem you are facing more quickly, please provide the following basic information.

1. **OS version**：_e.g. Ubuntu 18.04_
2. **Environment version:**  _Python / PyTorch / CUDA / cuDNN version_
3. **cvpods version**：_You can use `git log` to get the corresponding commit id_ 

The following information is recommended to be provided in **text** rather than _screenshots_ for future retrieval. If your needs do not apply, the following template can be modified, but please keep the content above this bank.

I ran the following command：
```bash

Put your command here.

```

Expect the following results：
```

Put expected output here.

```

Actual results：
```

Pur error message here.

```

**Comment by poodarchu** [comment]
please state your problem following the template and please provide more error messages rather than describe the bug only in your words.
