### ISSUE TITLE
visualize_data

### ISSUE THREAD

**Issue by shenhaibb** [Megvii-BaseDetection/cvpods#87]
visualiza_data.py Line 15 from cvpods.config import get_cfg

`python visualize_data.py --source annotation --config-file ./playground/detection/coco/auto_assign/auto_assign.res50.fpn.coco.800size.1x`
Traceback (most recent call last):
  File "visualize_data.py", line 15, in <module>
    from cvpods.config import get_cfg
ModuleNotFoundError: No module named 'cvpods.config'

how to visualize the results using the model i have trained

**Comment by shenhaibb** [comment]
hey, could u help me? do i need download detectron2?
when i run visualize_data.py, there are many errors encountered
`parser.add_argument("--config-file", default="", metavar="FILE", help="path to config file")` means ??
how to visualize @zengarden

**Comment by shenhaibb** [comment]
I have trained the model, and I need the visualization result of the model detection picture to supplement my paper.
How can I get the visualization result？
@poodarchu plz help me

**Comment by shenhaibb** [comment]
i have solved, use visualize_json_results.py....not visualize_data.py.....

**Comment by kinredon** [comment]
> 
@shenhaibb 
How to get the detection results? (a json file as the input for visualize_json_results.py)

**Comment by FionaZhangJ** [comment]
> > 
> 
> @shenhaibb How to get the detection results? (a json file as the input for visualize_json_results.py)

Did you solve the problem? I want to know it, too.  Thank you.
