### ISSUE TITLE
How to do inference on a single image?[Usage]

### ISSUE THREAD

**Issue by VladuxRTK** [Megvii-BaseDetection/cvpods#91]
**Please use this template to submit your problem or your question will _NOT_ be properly tackled.**

---

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?

I want to use an image from the susbset of test images from crowdhuman dataset.
I want to be able to run an inference on it and do the object detection on it, but there is no path assignment for pods_test...
Please tell me if there is a way for that

**Comment by poodarchu** [comment]
you can achieve this through modifying the dataset_dict in Dataset class, and only put your desired image into the dataset_dict. as a result, the length of the dataset will become 1.
