### ISSUE TITLE
How to use cvpods for obb detection[Usage]

### ISSUE THREAD

**Issue by BroenLin** [Megvii-BaseDetection/cvpods#99]
## ❓ How to use cvpods for obb detection?
I want to use the dataset DOTA, but it seems that cvpods only apply to bbox detection. For example, Class Instances only has "instances.gt_boxes = Boxes(...)". I don't know how to use it for obb detection.

**Comment by poodarchu** [comment]
You can:
1. Inherit Boxes and implement a new RotatedBoxes class to support extra dimensions.
2. Get rid of Boxes, Instances and simply annotations to plain numpy / pytorch arrays.
